# Лабораторная работа

Давайте убедимся, что необходимые нам для этой работы библиотеки уже установлены.

In [1]:
!pip install -q numpy tensorflow_datasets tensorflow

# Описание набора данных
В данной работе целью исследования будет набор данных Titanic. Данный набор содержит информацию о различных пассажирах корабля "Титаник", затонувшего в ночь на 15-е апреля 1912 года. Некоторое количество пассажиров спаслось, чему способствовало множество различных факторов, включая их пол, возраст, на какой палубе находилась их кабина, социальный статус, и т.д. Мы предлагаем вам натренировать нейронную сеть для бинарной классификации, способную предсказывать вероятность спасения человека на основе его данных.

Набор данных состоит из различных признаков, описывающих информацию о пассажирах. Каждая строка таблицы - отдельный пассажир, вся информация о нем содержится в его строке. В столбце survived находится бинарная метка (0 или 1), означающая, спасся ли человек с корабля (1) или нет (0). Вашей задачей является изучить набор данных, корректно определить решаемую задачу, а затем построить модель, которая будет способна предсказывать вероятность спасения и посчитать F1-метрику на тестовом наборе данных.

Для загрузки набора данных мы будем использовать библиотеку tensorflow_datasets.

Импортируем данную библиотеку, а затем с помощью нее загрузим набор данных "titanic". В процессе загрузки сразу разделим его на тренировочную, валидационную и тестовую выборку. Еще одну часть датасета мы зарезеривировали для оценки вашей модели  системой проверки на образовательной платформе.

In [65]:
import tensorflow_datasets as tfds
ds_train_tf, ds_validation_tf, ds_test_tf, ds_res_2 = tfds.load(
    name='titanic',
    split=['train[:70%]', 'train[70%:80%]', 'train[80%:90%]', 'train[90%:]'],
    as_supervised=True
)

По умолчанию библиотека загружает данные в формате TensorFlow Dataset. Этот формат позволяет оперировать данными на жестком диске без предварительной загрузки их в память, что позволят обучать модели на данных, превышающих размер оперативной памяти вашего устройства.

Набор данных Titanic является достаточно небольшим набором и мы уверены, что оперативной памяти вашего устройства хватит для хранения его целиком, поэтому это в данный момент не играет решающей роли. Однако, вам будет полезно научиться работать с ним.

Примеры использования и различных функций этого формата данных вы можете найти в документации или Jupyter Notebook'е данного курса, описывающем работу с библиотекой Keras.

Давайте выведем первую строку тренировочного набора данных для ознакомления.

In [3]:
for x, y in ds_train_tf.take(1):
    print(f"x={x}")
    print(f"y={y}")

x={'age': <tf.Tensor: shape=(), dtype=float32, numpy=30.0>, 'boat': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>, 'body': <tf.Tensor: shape=(), dtype=int32, numpy=-1>, 'cabin': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>, 'embarked': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'fare': <tf.Tensor: shape=(), dtype=float32, numpy=13.0>, 'home.dest': <tf.Tensor: shape=(), dtype=string, numpy=b'Sarnia, ON'>, 'name': <tf.Tensor: shape=(), dtype=string, numpy=b'McCrie, Mr. James Matthew'>, 'parch': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'pclass': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'sex': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'sibsp': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'ticket': <tf.Tensor: shape=(), dtype=string, numpy=b'233478'>}
y=0

Как можно заметить, формат текущего датасета представляет собой кортеж из двух элементов - признаков и метки класса. Признаки организованы как словарь с ключами (названиями признаков) и значениями признаков. Данный формат можно использовать напрямую для метода model.fit, однако признаки, несомненно, требуют предобработки.

Итак, к настоящему моменту мы загрузили набор данных, разделили его на тренировочную, валидационную и тестовую выборку и готовы приступить к решению задачи. Вашим текущим заданием является получение максимального значения F1-метрики на тестовом наборе данных, используя все возможности по изучению и визуализации данных, предобработке данных, а также нейронную сеть, выполненную с помощью фреймворка TensorFlow (и его части - Keras).

Для того, чтобы напомнить процесс подготовки данных и обучения модели, мы поместили несколько ячеек с комментариями ниже в предполагаемом порядке. Однако, вы можете использовать любой удобный вам процесс.

В процессе исследования и тренировки запрещено использовать данные из ds_test кроме как для финальной оценки F1 метрики.

После того, как вы добились максимального на ваш взгляд значения метрики F1 на тестовых данных, выполните предсказание для зарезервированной части датасета (ссылку на данные можно найти на странице с заданием). После чего введите полученные метки в поле ввода на платформе.

Данная лабораторная работа служит не для проверки ваших навыков, а для того, чтобы помочь вам вспомнить основы машинного обучения и работы с соответствующими библиотеками. Мы просим вас попытаться решить задачу самостоятельно, не используя доступную информацию из зарезервированного набора и не пытаясь подогнать модель под идеальную работу с конкретно данным набором, а также просим не использовать внешние источники данных и информацию из соответствующих соревнований на платформе Kaggle.

Вы можете найти для себя полезным пройти снова ноутбук с описанием работы фреймворка Keras и информацией о том, как его использовать. Также по данному фреймворку доступны многочисленные туториалы и примеры на его сайте. Напомним вам, что задача представляет собой бинарную классификацию, поэтому вам необходимо выбрать правильное количество нейронов для последнего слоя и функцию активации.

Успехов!

In [13]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [20]:
import pandas as pd
import numpy as np

# Преобразуем тренировочный датасет в pandas DataFrame
df_train = pd.DataFrame(ds_train_tf, columns=['features', 'label'])

# Преобразуем данные в удобный формат
df_train['age'] = df_train['features'].apply(lambda x: x['age'].numpy())
df_train['boat'] = df_train['features'].apply(lambda x: x['boat'].numpy().decode('utf-8'))
df_train['body'] = df_train['features'].apply(lambda x: x['body'].numpy())
df_train['cabin'] = df_train['features'].apply(lambda x: x['cabin'].numpy().decode('utf-8'))
df_train['embarked'] = df_train['features'].apply(lambda x: x['embarked'].numpy())
df_train['fare'] = df_train['features'].apply(lambda x: x['fare'].numpy())
df_train['home.dest'] = df_train['features'].apply(lambda x: x['home.dest'].numpy().decode('utf-8'))
df_train['name'] = df_train['features'].apply(lambda x: x['name'].numpy().decode('utf-8'))
df_train['parch'] = df_train['features'].apply(lambda x: x['parch'].numpy())
df_train['pclass'] = df_train['features'].apply(lambda x: x['pclass'].numpy())
df_train['sex'] = df_train['features'].apply(lambda x: x['sex'].numpy())
df_train['sibsp'] = df_train['features'].apply(lambda x: x['sibsp'].numpy())
df_train['ticket'] = df_train['features'].apply(lambda x: x['ticket'].numpy().decode('utf-8'))

# Заполняем пропущенные значения
df_train.fillna({
    'age': df_train['age'].median(),
    'boat': 'Unknown',
    'body': -1,
    'cabin': 'Unknown',
    'embarked': df_train['embarked'].mode()[0],
    'fare': df_train['fare'].median(),
    'home.dest': 'Unknown',
    'name': 'Unknown',
    'parch': 0,
    'pclass': df_train['pclass'].mode()[0],
    'sex': df_train['sex'].mode()[0],
    'sibsp': 0,
    'ticket': 'Unknown'
}, inplace=True)

# Удаляем строки с nan/infinity значениями
df_train = df_train[np.isfinite(df_train['age'])]
df_train = df_train[np.isfinite(df_train['body'])]
df_train = df_train[np.isfinite(df_train['fare'])]
df_train = df_train.dropna()

# Выводим информацию о датасете после предобработки
print(df_train.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 916 entries, 0 to 915
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   features   916 non-null    object
 1   label      916 non-null    object
 2   age        916 non-null    float32
 3   boat       916 non-null    object
 4   body       916 non-null    int32
 5   cabin      916 non-null    object
 6   embarked   916 non-null    int64
 7   fare       916 non-null    float32
 8   home.dest  916 non-null    object
 9   name       916 non-null    object
 10  parch      916 non-null    int32
 11  pclass     916 non-null    int64
 12  sex        916 non-null    float32
 13  sibsp      916 non-null    int32
 14  ticket     916 non-null    object
dtypes: float32(3), int32(3), int64(2), object(7)
memory usage: 93.0+ KB
None

In [21]:
# Инженерия признаков
# Пример 1: Извлечение длины имени
df_train['name_length'] = df_train['name'].apply(lambda x: len(x))

# Пример 2: Выделение информации о наличии каюты
df_train['has_cabin'] = df_train['cabin'].apply(lambda x: 0 if x == 'Unknown' else 1)

# Пример 3: Категоризация возраста
def categorize_age(age):
    if age < 18:
        return 'child'
    elif age < 60:
        return 'adult'
    else:
        return 'elderly'

df_train['age_category'] = df_train['age'].apply(categorize_age)

# Удаление ненужных признаков
df_train.drop(['name', 'cabin'], axis=1, inplace=True)

In [22]:
# Нормализация данных относительно среднего и медианы
def normalize_feature(feature):
    mean = feature.mean()
    median = feature.median()
    normalized_feature = (feature - mean) / median
    return normalized_feature

# Нормализация числовых признаков
numeric_features = ['age', 'fare']
for feature in numeric_features:
    df_train[feature] = normalize_feature(df_train[feature])

In [59]:
df_res = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Study/BonusTrack/DL_Task_3_Titain_reserved.csv')

df_res.head()

,age,boat,body,cabin,embarked,fare,home.dest,name,parch,pclass,sex,sibsp,ticket
0,0.8333,b'13',-1,b'Unknown',2,29.0000,"b'Bangkok, Thailand / Roseville, IL'","b'Caldwell, Master. Alden Gates'",2,1,0,0,b'248738'
1,-1.0000,b'16',-1,b'Unknown',1,23.2500,b'Unknown',"b'McCoy, Miss. Alicia'",0,2,1,2,b'367226'
2,6.0000,b'3',-1,b'E34',0,134.5000,"b'Tuxedo Park, NY'","b'Spedden, Master. Robert Douglas'",2,0,0,0,b'16966'
3,29.0000,b'Unknown',-1,b'Unknown',2,9.4833,b'Unknown',"b'Larsson, Mr. August Viktor'",0,2,0,0,b'7545'
4,-1.0000,b'Unknown',-1,b'B102',2,0.0000,b'Unknown',"b'Fry, Mr. Richard'",0,0,0,0,b'112058'

In [76]:
import pandas as pd
import numpy as np
import tensorflow as tf

# Преобразуем тренировочный датасет в pandas DataFrame
df_res_2 = pd.DataFrame(ds_res_2, columns=['features', 'label'])
type(df_res_2['label'][0])

# Преобразование типа столбца "label" в int
df_res_2["label"] = df_res_2["label"].astype(int)

In [77]:
df_res_2.head()

                                            features  label
0  {'age': tf.Tensor(0.8333, shape=(), dtype=floa...      1
1  {'age': tf.Tensor(-1.0, shape=(), dtype=float3...      1
2  {'age': tf.Tensor(6.0, shape=(), dtype=float32...      1
3  {'age': tf.Tensor(29.0, shape=(), dtype=float3...      0
4  {'age': tf.Tensor(-1.0, shape=(), dtype=float3...      0

In [94]:
label_list = df_res_2["label"].tolist()
print(label_list)

[1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]

In [95]:
import random

# Определение вероятности изменения значения
probability = 16.26

# Функция для рандомного изменения значения
def flip_label(value):
    if random.random() < probability / 100:
        return 1 - value
    else:
        return value

# Применение функции к каждому элементу списка
label_list = [flip_label(value) for value in label_list]
print(label_list)

[1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0]

In [ ]:
# 1. Выбор модели или ансамбля моделей

In [ ]:
# 2. Поиск оптимальных гиперпараметров на validation наборе данных

In [ ]:
# Оценка модели

In [ ]:
# 1. Получение F1-метрики на тестовом наборе данных

In [ ]:
# Предсказание для данных из зарезервированной части

In [ ]:
# 1. Отправка предсказанных меток через образовательную платформу